services:
  postgres:
    image: postgres:16
    container_name: retailiq-db

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - retailiq-network
  jenkins:
    build:
      context: ./jenkins

    container_name: retailiq-jenkins

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace

    networks:
      - retailiq-network
  backend:
    build:
      context: ./backend

    container_name: retailiq-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_HOST: ${REDIS_HOST}
      SECRET_KEY: ${SECRET_KEY}

    volumes:
      - backend_uploads:/app/uploads
    
    networks:
      - retailiq-network

  frontend:
    build:
      context: ./frontend

    container_name: retailiq-frontend

    ports:
      - "3000:3000"
    
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}

    depends_on:
      - backend
    
    networks:
      - retailiq-network
  redis:
    image: redis:7

    container_name: retailiq-redis

    ports:
      - "6379:6379"
    
    volumes:
      - redis_data:/data
    
    networks:
      - retailiq-network
  
  prometheus:
    image: prom/prometheus

    container_name: retailiq-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend
    
    networks:
      - retailiq-network
  
  grafana:
    image: grafana/grafana

    container_name: retailiq-grafana

    ports:
      - "3001:3000"
    
    volumes:
      - grafana_data:/var/lib/grafana

    depends_on:
      - prometheus
    
    networks:
      - retailiq-network

volumes:
  backend_uploads:
    external: true
    name: retailiq-backend-upload-data
  postgres_data:
    external: true
    name: retailiq-postgres-data

  redis_data:
    external: true
    name: retailiq-redis-data

  grafana_data:
    external: true
    name: retailiq-grafana-data
  
  jenkins_data:
    external: true
    name: retailiq-jenkins-data

networks:
  retailiq-network:
    external: true