version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: retailiq-db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: retailiq

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: retailiq-backend

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

    environment:
      REDIS_HOST: redis

    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend

    container_name: retailiq-frontend

    ports:
      - "3000:3000"

    depends_on:
      - backend
  redis:
    image: redis:7

    container_name: retailiq-redis

    ports:
      - "6379:6379"
  
  prometheus:
    image: prom/prometheus

    container_name: retailiq-prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml

    depends_on:
      - backend
  
  grafana:
    image: grafana/grafana

    container_name: retailiq-grafana

    ports:
      - "3001:3000"

    depends_on:
      - prometheus

volumes:
  postgres_data: