apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: retailiq-backend

          imagePullPolicy: Never

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: retailiq-secret
                  key: DATABASE_URL

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: retailiq-config
                  key: REDIS_HOST