---
- name: Apply Kubernetes Resources
  command: kubectl apply -f k8s/
  args:
    chdir: "{{ playbook_dir }}/.."

- name: Wait for Backend Deployment
  command: kubectl rollout status deployment/backend
  register: backend_rollout
  changed_when: false

- debug:
    var: backend_rollout.stdout_lines

- name: Wait for Frontend Deployment
  command: kubectl rollout status deployment/frontend
  register: frontend_rollout
  changed_when: false

- debug:
    var: frontend_rollout.stdout_lines

- name: Wait for Postgres Deployment
  command: kubectl rollout status deployment/postgres
  register: postgres_rollout
  changed_when: false

- debug:
    var: postgres_rollout.stdout_lines

- name: Get Pods
  command: kubectl get pods
  register: pods
  changed_when: false

- debug:
    var: pods.stdout_lines

- name: Get Services
  command: kubectl get svc
  register: services
  changed_when: false

- debug:
    var: services.stdout_lines