"""add product column

Revision ID: 058cb8ed38f8
Revises: f9c19e2efcef
Create Date: 2026-06-08 19:07:11.241402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '058cb8ed38f8'
down_revision: Union[str, Sequence[str], None] = 'f9c19e2efcef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('column_mappings', sa.Column('product_column', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('column_mappings', 'product_column')
    # ### end Alembic commands ###
