"""create column mappings table

Revision ID: f9c19e2efcef
Revises: 2819f346da59
Create Date: 2026-06-08 18:16:50.104232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9c19e2efcef'
down_revision: Union[str, Sequence[str], None] = '2819f346da59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('column_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('customer_column', sa.String(length=100), nullable=False),
    sa.Column('date_column', sa.String(length=100), nullable=False),
    sa.Column('quantity_column', sa.String(length=100), nullable=False),
    sa.Column('price_column', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('column_mappings')
    # ### end Alembic commands ###
