---
- name: Check Python
  command: python3 --version
  register: python_version
  changed_when: false

- debug:
    var: python_version.stdout_lines

- name: Check Node
  command: node --version
  register: node_version
  changed_when: false

- debug:
    var: node_version.stdout_lines

- name: Check npm
  command: npm --version
  register: npm_version
  changed_when: false

- debug:
    var: npm_version.stdout_lines

- name: Check Terraform
  command: terraform version
  register: terraform_version
  changed_when: false

- debug:
    var: terraform_version.stdout_lines

- name: Check Docker CLI
  command: docker --version
  register: docker_version
  changed_when: false

- debug:
    var: docker_version.stdout_lines

- name: Check Docker Compose
  command: docker compose version
  register: compose_version
  changed_when: false

- debug:
    var: compose_version.stdout_lines

- name: Check kubectl
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- debug:
    var: kubectl_version.stdout_lines

- name: Check Ansible
  command: ansible --version
  register: ansible_version
  changed_when: false

- debug:
    var: ansible_version.stdout_lines