---
- name: Check Docker
  command: docker --version
  register: docker_version
  changed_when: false

- debug:
    var: docker_version.stdout_lines

- name: Check kubectl
  command: kubectl version --client
  register: kubectl_version
  changed_when: false

- debug:
    var: kubectl_version.stdout_lines

- name: Check Minikube
  command: minikube version
  register: minikube_version
  changed_when: false

- debug:
    var: minikube_version.stdout_lines

- name: Check Git
  command: git --version
  register: git_version
  changed_when: false

- debug:
    var: git_version.stdout_lines