---
- name: Deploy RetailIQ
  hosts: azure
  become: true
  gather_facts: true

  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

  roles:
    - docker
    - kubernetes
    - retailiq
    - checks