name: RetailIQ CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  backend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Verify Imports
        run: |
          python -c "import fastapi"
          python -c "import sqlalchemy"
          python -c "import pandas"

      - name: Build Backend Docker Image
        run: |
          docker build -t retailiq-backend .

  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install

      - name: Build NextJS
        run: npm run build

      - name: Build Frontend Docker Image
        run: |
          docker build -t retailiq-frontend .